### ISSUE TITLE
Add list & remove functionalities to rhumba

### ISSUE THREAD

**Issue by marimeireles** [mamba-org/rhumba#3]

**Comment by marimeireles** [comment]
I have added list but it's not working. Probably because I didn't run a `Rcpp::export()`?

**Comment by wolfv** [comment]
It would be even cooler to give R access to the installed package data in a R native format (e.g. a data table or something like that)

**Comment by marimeireles** [comment]
@wolfv is it a problem that when installing packages rhumba doesn't create a `pkgs` dir?
It only has a `bin`. We can have a look at this tomorrow if you wanna/can meetup =)
